using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Finance_tracker.Account
{
    public partial class CountryInfo
    {
        public string CountryCode { get; set; }
        public string PhoneNumberFormat { get; set; }

        public CountryInfo(string code, string format)
        {
            CountryCode = code;
            PhoneNumberFormat = format;
        }
        Dictionary<string, CountryInfo> countryInfoDictionary = new Dictionary<string, CountryInfo>
        {
            { "Afghanistan", new CountryInfo("+93", "xx xx xx xx xx") },
            { "Albania", new CountryInfo("+355", "xx xxx xxxx") },
            { "Algeria", new CountryInfo("+213", "xx xx xx xx xx") },
            { "Andorra", new CountryInfo("+376", "xx xx xx") },
            { "Angola", new CountryInfo("+244", "xxx xxx xxx") },
            { "Antigua and Barbuda", new CountryInfo("+1-268", "xxx-xxxx") },
            { "Argentina", new CountryInfo("+54", "x xxxx-xxxx") },
            { "Armenia", new CountryInfo("+374", "xx xxxxxx") },
            { "Australia", new CountryInfo("+61", "x xxxx xxxx") },
            { "Austria", new CountryInfo("+43", "xxxx xxxxxx") },
            { "Azerbaijan", new CountryInfo("+994", "xx xxx xx xx") },
            { "The Bahamas", new CountryInfo("+1-242", "xxx-xxxx") },
            { "Bahrain", new CountryInfo("+973", "xxxx xxxx") },
            { "Bangladesh", new CountryInfo("+880", "xx xxx xxxx") },
            { "Barbados", new CountryInfo("+1-246", "xxx-xxxx") },
            { "Belarus", new CountryInfo("+375", "xx xxx xx xx") },
            { "Belgium", new CountryInfo("+32", "xx xx xx xx xx") },
            { "Belize", new CountryInfo("+501", "xxxx xxxx") },
            { "Benin", new CountryInfo("+229", "xx xx xx xx") },
            { "Bhutan", new CountryInfo("+975", "xx xx xxxx") },
            { "Bolivia", new CountryInfo("+591", "xxx xxxx-xxxx") },
            { "Bosnia and Herzegovina", new CountryInfo("+387", "xx xxx xxx") },
            { "Botswana", new CountryInfo("+267", "xx xxx xxx") },
            { "Brazil", new CountryInfo("+55", "xx xxxx-xxxx") },
            { "Brunei", new CountryInfo("+673", "xxxx xxxx") },
            { "Bulgaria", new CountryInfo("+359", "xx xxx xxxx") },
            { "Burkina Faso", new CountryInfo("+226", "xx xx xx xx") },
            { "Burundi", new CountryInfo("+257", "xx xx xx xx") },
            { "Cabo Verde", new CountryInfo("+238", "xxx xx xx") },
            { "Cambodia", new CountryInfo("+855", "xx xxx xxx") },
            { "Cameroon", new CountryInfo("+237", "xx xx xx xx xx") },
            { "Canada", new CountryInfo("+1", "xxx-xxx-xxxx") },
            { "Central African Republic", new CountryInfo("+236", "xx xx xx xx") },
            { "Chad", new CountryInfo("+235", "xx xx xx xx") },
            { "Chile", new CountryInfo("+56", "x xxxx xxxx") },
            { "China", new CountryInfo("+86", "xx xxxx-xxxx") },
            { "Colombia", new CountryInfo("+57", "xxx xxx xxxx") },
            { "Comoros", new CountryInfo("+269", "xx xx xx xx") },
            { "Congo", new CountryInfo("+242", "xx xx xx xx xx") },
            { "Costa Rica", new CountryInfo("+506", "xxxx-xxxx") },
            { "Côte d’Ivoire", new CountryInfo("+225", "xx xx xx xx") },
            { "Croatia", new CountryInfo("+385", "xx xxx xxx") },
            { "Cuba", new CountryInfo("+53", "xx xxx xxxx") },
            { "Cyprus", new CountryInfo("+357", "xx xxxxxx") },
            { "Czech Republic", new CountryInfo("+420", "xxx xxx xxx") },
            { "Denmark", new CountryInfo("+45", "xx xx xx xx") },
            { "Djibouti", new CountryInfo("+253", "xx xx xx xx") },
            { "Dominica", new CountryInfo("+1-767", "xxx-xxxx") },
            { "Dominican Republic", new CountryInfo("+1-809", "xxx-xxxx") },
            { "East Timor (Timor-Leste)", new CountryInfo("+670", "xxxx xxxx") },
            { "Ecuador", new CountryInfo("+593", "xx xxx xxxx") },
            { "Egypt", new CountryInfo("+20", "xx xxx xxxx") },
            { "El Salvador", new CountryInfo("+503", "xxxx xxxx") },
            { "Equatorial Guinea", new CountryInfo("+240", "xx xx xx xx") },
            { "Eritrea", new CountryInfo("+291", "xx xx xx xx") },
            { "Estonia", new CountryInfo("+372", "xxxx xxxx") },
            { "Eswatini", new CountryInfo("+268", "xx xx xx xx") },
            { "Ethiopia", new CountryInfo("+251", "xx xxx xxxx") },
            { "Fiji", new CountryInfo("+679", "xxxx xxxx") },
            { "Finland", new CountryInfo("+358", "xx xxx xxxx") },
            { "France", new CountryInfo("+33", "xx xx xx xx xx") },
            { "Gabon", new CountryInfo("+241", "xx xx xx xx") },
            { "The Gambia", new CountryInfo("+220", "xxx xxxx") },
            { "Georgia", new CountryInfo("+995", "xxx xxxxxx") },
            { "Germany", new CountryInfo("+49", "xxxx xxxxxxx") },
            { "Ghana", new CountryInfo("+233", "xx xxx xxxx") },
            { "Greece", new CountryInfo("+30", "xxx xxx xxxx") },
            { "Grenada", new CountryInfo("+1-473", "xxx-xxxx") },
            { "Guatemala", new CountryInfo("+502", "xxxx-xxxx") },
            { "Guinea", new CountryInfo("+224", "xx xx xx xx") },
            { "Guinea-Bissau", new CountryInfo("+245", "xx xx xx xx") },
            { "Guyana", new CountryInfo("+592", "xxx-xxxx") },
            { "Haiti", new CountryInfo("+509", "xxxx-xxxx") },
            { "Honduras", new CountryInfo("+504", "xxxx-xxxx") },
            { "Hungary", new CountryInfo("+36", "xx xxx xxxx") },
            { "Iceland", new CountryInfo("+354", "xxx xxxx") },
            { "India", new CountryInfo("+91", "xxxxx xxxxx") },
            { "Indonesia", new CountryInfo("+62", "xxxx-xxxx-xxxx") },
            { "Iran", new CountryInfo("+98", "xx xxxxx xxxxx") },
            { "Iraq", new CountryInfo("+964", "xx xxx xxxx") },
            { "Ireland", new CountryInfo("+353", "xx xxx xxxx") },
            { "Israel", new CountryInfo("+972", "xx xxx xxxx") },
            { "Italy", new CountryInfo("+39", "xxx xxx xxxx") },
            { "Jamaica", new CountryInfo("+1-876", "xxx-xxxx") },
            { "Japan", new CountryInfo("+81", "xx-xxxx-xxxx") },
            { "Jordan", new CountryInfo("+962", "xx xxx xxxx") },
            { "Kazakhstan", new CountryInfo("+7", "x xxx xxx-xx-xx") },
            { "Kenya", new CountryInfo("+254", "xx xxx xxxx") },
            { "Kiribati", new CountryInfo("+686", "xxx-xxxx") },
            { "Korea, North", new CountryInfo("+850", "xxxx-xxxx") },
            { "Korea, South", new CountryInfo("+82", "xx-xxxx-xxxx") },
            { "Kosovo", new CountryInfo("+383", "xx xx xx xx xx") },
            { "Kuwait", new CountryInfo("+965", "xxxx xxxx") },
            { "Kyrgyzstan", new CountryInfo("+996", "xx xxx-xxxx") },
            { "Laos", new CountryInfo("+856", "xx xx xxxx xxxx") },
            { "Latvia", new CountryInfo("+371", "xxxx xxxx") },
            { "Lebanon", new CountryInfo("+961", "xx xxx xxx") },
            { "Lesotho", new CountryInfo("+266", "xx xx xx xx") },
            { "Liberia", new CountryInfo("+231", "xx xx xx xx") },
            { "Libya", new CountryInfo("+218", "xx xxx xxxx") },
            { "Liechtenstein", new CountryInfo("+423", "xxx xxxx") },
            { "Lithuania", new CountryInfo("+370", "xxx xxxxx") },
            { "Luxembourg", new CountryInfo("+352", "xx xx xx xx") },
            { "Madagascar", new CountryInfo("+261", "xx xx xx xx xx") },
            { "Malawi", new CountryInfo("+265", "xx xx xx xx xx") },
            { "Malaysia", new CountryInfo("+60", "xx-xxxx xxxx") },
            { "Maldives", new CountryInfo("+960", "xxxx xxx") },
            { "Mali", new CountryInfo("+223", "xx xx xx xx") },
            { "Malta", new CountryInfo("+356", "xx xx xx xx") },
            { "Marshall Islands", new CountryInfo("+692", "xxx-xxxx") },
            { "Mauritania", new CountryInfo("+222", "xx xx xx xx") },
            { "Mauritius", new CountryInfo("+230", "xx xx xx xx") },
            { "Mexico", new CountryInfo("+52", "xxx xxx xxx xxxx") },
            { "Micronesia", new CountryInfo("+691", "xxx-xxxx") },
            { "Moldova", new CountryInfo("+373", "xx xxx xxx") },
            { "Monaco", new CountryInfo("+377", "xx xx xx xx xx") },
            { "Mongolia", new CountryInfo("+976", "xx xx xx xx") },
            { "Montenegro", new CountryInfo("+382", "xx xx xx xx") },
            { "Morocco", new CountryInfo("+212", "xx xx xx xx xx") },
            { "Mozambique", new CountryInfo("+258", "xx xx xx xx xx") },
            { "Myanmar (Burma)", new CountryInfo("+95", "xx xx xx xx xx") },
            { "Namibia", new CountryInfo("+264", "xx xx xx xx") },
            { "Nauru", new CountryInfo("+674", "xxx-xxxx") },
            { "Nepal", new CountryInfo("+977", "xx xxxx xxxx") },
            { "Netherlands", new CountryInfo("+31", "xx xx xx xx xx") },
            { "New Zealand", new CountryInfo("+64", "x xxxx xxxx") },
            { "Nicaragua", new CountryInfo("+505", "xxxx-xxxx") },
            { "Niger", new CountryInfo("+227", "xx xx xx xx") },
            { "Nigeria", new CountryInfo("+234", "xxx xxx xxxx") },
            { "North Macedonia", new CountryInfo("+389", "xx xxx xxx") },
            { "Norway", new CountryInfo("+47", "xx xx xx xx") },
            { "Oman", new CountryInfo("+968", "xxxx xxxx") },
            { "Pakistan", new CountryInfo("+92", "xxx xxxxxxx") },
            { "Palau", new CountryInfo("+680", "xxx-xxxx") },
            { "Panama", new CountryInfo("+507", "xxxx-xxxx") },
            { "Papua New Guinea", new CountryInfo("+675", "xxx-xxxx") },
            { "Paraguay", new CountryInfo("+595", "xxx xxxxxx") },
            { "Peru", new CountryInfo("+51", "xx xxx xxxx") },
            { "Philippines", new CountryInfo("+63", "xxxx-xxxx") },
            { "Poland", new CountryInfo("+48", "xxx xxx xxx") },
            { "Portugal", new CountryInfo("+351", "xx xxx xxxx") },
            { "Qatar", new CountryInfo("+974", "xxxx xxxx") },
            { "Romania", new CountryInfo("+40", "xxx xxx xxx") },
            { "Russia", new CountryInfo("+7", "x xxx xxx-xx-xx") },
            { "Rwanda", new CountryInfo("+250", "xx xxx xxxx") },
            { "Saint Kitts and Nevis", new CountryInfo("+1-869", "xxx-xxxx") },
            { "Saint Lucia", new CountryInfo("+1-758", "xxx-xxxx") },
            { "Saint Vincent and the Grenadines", new CountryInfo("+1-784", "xxx-xxxx") },
            { "Samoa", new CountryInfo("+685", "xxxxxx") },
            { "San Marino", new CountryInfo("+378", "xxxxx") },
            { "Sao Tome and Principe", new CountryInfo("+239", "xx xx xx xx") },
            { "Saudi Arabia", new CountryInfo("+966", "xx xxx xxxx") },
            { "Senegal", new CountryInfo("+221", "xx xx xx xx xx") },
            { "Serbia", new CountryInfo("+381", "xx xxx xxxxx") },
            { "Seychelles", new CountryInfo("+248", "x xx xx xx xx") },
            { "Sierra Leone", new CountryInfo("+232", "xx xxxxxx") },
            { "Singapore", new CountryInfo("+65", "xxxx xxxx") },
            { "Slovakia", new CountryInfo("+421", "xxx xxx xxxx") },
            { "Slovenia", new CountryInfo("+386", "xx xxx xxxx") },
            { "Solomon Islands", new CountryInfo("+677", "xxx-xxxx") },
            { "Somalia", new CountryInfo("+252", "xx xxx xxxx") },
            { "South Africa", new CountryInfo("+27", "xx xxx xxxx") },
            { "Spain", new CountryInfo("+34", "xxx xx xx xx") },
            { "Sri Lanka", new CountryInfo("+94", "xx-xxxxxxx") },
            { "Sudan", new CountryInfo("+249", "xx xxx xxxx") },
            { "Sudan, South", new CountryInfo("+211", "xx xxx xxx xxxx") },
            { "Suriname", new CountryInfo("+597", "xxx-xxxx") },
            { "Sweden", new CountryInfo("+46", "xx-xxxxxx") },
            { "Switzerland", new CountryInfo("+41", "xx xxx xx xx") },
            { "Syria", new CountryInfo("+963", "xx xxx xxxx") },
            { "Taiwan", new CountryInfo("+886", "xxxx-xxxxxx") },
            { "Tajikistan", new CountryInfo("+992", "xx xxx xx xx xx") },
            { "Tanzania", new CountryInfo("+255", "xx xxx xxx xxxx") },
            { "Thailand", new CountryInfo("+66", "xx-xxxx-xxxx") },
            { "Togo", new CountryInfo("+228", "xx xx xx xx") },
            { "Tonga", new CountryInfo("+676", "xxxx") },
            { "Trinidad and Tobago", new CountryInfo("+1-868", "xxx-xxxx") },
            { "Tunisia", new CountryInfo("+216", "xx xxx xxx") },
            { "Turkey", new CountryInfo("+90", "xxx xxx xxxx") },
            { "Turkmenistan", new CountryInfo("+993", "xx xxxxxx") },
            { "Tuvalu", new CountryInfo("+688", "xxxx") },
            { "Uganda", new CountryInfo("+256", "xx xxx xxxx") },
            { "Ukraine", new CountryInfo("+380", "xx xxx xxx xx") },
            { "United Arab Emirates", new CountryInfo("+971", "xx xxx xxxx") },
            { "United Kingdom", new CountryInfo("+44", "xxxx xxx xxxx") },
            { "United States", new CountryInfo("+1", "xxx-xxx-xxxx") },
            { "Uruguay", new CountryInfo("+598", "xx xx xx xx xx") },
            { "Uzbekistan", new CountryInfo("+998", "xx xxx xx xx xx") },
            { "Vanuatu", new CountryInfo("+678", "xxxxxx") },
            { "Vatican City", new CountryInfo("+379", "xxxxx") },
            { "Venezuela", new CountryInfo("+58", "xx xxx-xxxxxxx") },
            { "Vietnam", new CountryInfo("+84", "xx xxxx xxxx") },
            { "Yemen", new CountryInfo("+967", "xx xxx xxxx") },
            { "Zambia", new CountryInfo("+260", "xx xxxx xxxx") },
            { "Zimbabwe", new CountryInfo("+263", "xx xxx xxxx") }
        };
    }
}
